mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
]

mysite/news/urls.py
from django.urls import path

from . import views
app_name = 'news'

urlpatterns = [
    path('', views.IndexView, name='index'),
    path('<int:id>/', views.DetailView.as_view(), name='detail'),
]

mysite/news/models.py
from django.db import models

# Create your models here.

class News(models.Model):
    #id = models.IntegerField(primary_key=True)
    title = models.CharField('标题', max_length=70)
    # 文章标题，CharField 表示对应数据库中表的列是用来存字符串的，'标题'是一个位置参数
    # （verbose_name），主要用于 django 的后台系统，不多做介绍。max_length 表示能存储的字符串
    # 的最大长度
    article_content = models.TextField('正文')
    # 文章正文，TextField 用来存储大文本字符
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    # 文章创建时间，DateTimeField用于存储时间，设定auto_now_add参数为真，则在文章被创建时会自动添加创建时间
    last_modified_time = models.DateTimeField('修改时间', auto_now=True)
    # 文章最后一次编辑时间，auto_now=True表示每次修改文章时自动添加修改的时间

    #upload_path = models.FileField(upload_to='uploads/%Y/%m/%d', blank=True, null=True)
    # 文章存放位置

    article_image = models.FileField(upload_to='photos/%Y/%m/%d', blank=True, null=True)
    # 图片存放位置

    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
    )
    status = models.CharField('文章状态', max_length=1,
                                         choices=STATUS_CHOICES)
    # STATUS_CHOICES，field 的 choices 参数需要的值，choices选项会使该field在被渲染成form时被渲染为一个select组件，
    # 这里我定义了两个状态，一个是Draft（草稿），一个是Published（已发布），
    # select组件会有两个选项：Draft 和 Published。
    # 但是存储在数据库中的值分别是'd'和'p'，
    # 这就是 choices的作用。
    ARTICLE_TYPES = (
        ('1', '国内新闻'),
        ('2', '国际新闻'),
        ('3', '科技'),
        ('4', '焦点'),
    )
    category = models.CharField('Category', max_length=1,
                                             choices=ARTICLE_TYPES)


    views = models.PositiveIntegerField('浏览量', default=0)
    # 阅览量，PositiveIntegerField存储非负整数

    def __str__(self):
        # 主要用于交互解释器显示表示该类的字符串
        return self.title

mysite/news/views.py
from django.shortcuts import render
from django.views import generic
from .models import News

# Create your views here.

def IndexView (request):
    hot_list = News.objects.filter().order_by('-created_time')[:12]
    image_text = News.objects.exclude(article_image='None').order_by('-created_time')[:1]
    break_list1 = News.objects.filter(category='china').order_by('-created_time')[:13]
    break_list2 = News.objects.filter(category='international').order_by('-created_time')[:13]
    break_list3 = News.objects.filter(category='science').order_by('-created_time')[:13]
    news_list = {'hot_list': hot_list, 'image_text': image_text, 'break_list1': break_list1,
            'break_list2': break_list2, 'break_list3': break_list3}
    print(image_text[0].article_image)
    return render(request, "news/index.html",
                  {'hot_list': hot_list, 'image_text': image_text, 'break_list1': break_list1,
                    'break_list2': break_list2, 'break_list3': break_list3}
                  )



class DetailView(generic.DetailView):
    model = News
    template_name = 'news/detail.html'
    context_object_name = 'news'
    pk_url_kwarg = 'id'

    def get_object(self, queryset=None):
        obj = super(DetailView, self).get_object()
        print(obj)
        return obj

mysite/news/templates/news/detail.html
{% load static %}
{% if news %}

<html lang="en" >
	<head>


<title>{{news}}</title>

<link rel="stylesheet" type="text/css" href="{% static 'news/css/bootstrap.3.3.0.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'news/css/style-zbsg.css' %}">
<link href="{% static 'news/css/css' %}" rel="stylesheet">
<body class="html not-front not-logged-in no-sidebars page-node page-node- page-node-904581 node-type-article article-page section-0-znews section-1-greater-china" style="">

<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PMPGTV3"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
  	   <div id="block-dfp-topoverlay" class="block block-dfp">
  <div class="content">
    <div id="dfp-ad-topoverlay-wrapper" class="dfp-tag-wrapper">
<div id="dfp-ad-topoverlay" class="dfp-tag-wrapper" data-override="1">

</div>
</div>  </div>
</div>
<div id="block-block-25" class="block block-block">
  <div class="content">


<section id="brand" class="brand-global">
  <header>



<style>
@keyframes fade{
	0%{opacity:1;}
	25%{opacity:1;}
	75%{opacity:0;}
	100%{opacity:0;}
}

.spinner{height:34px;width:34px;margin:-4px 2px 0 0;position:relative;color:#fff;display:inline-block;}
.spinner:before{position:absolute;content:'';height:calc(100% + 1px);width:calc(100% + 1px);border:2px dotted #ffcc00;top:0;left:0;border-radius:inherit;animation:spin 10s linear infinite;}
.spinner,.spinner img{border-radius:50%;-moz-border-radius:50%;-khtml-border-radius:50%;-webkit-border-radius:50%;}
.spinner img{width:29px!important;margin:3px;}
img.spin{display:inline-block;width:30px!important;height:auto!important;margin:-2px 2px 0 0;animation:spin 4s linear infinite;}
@keyframes spin{
100%{transform: rotateZ(360deg);}
}
</style>

    <div id="zaobao-id" class="row">
      <div id="zaobao-brand">
				<a href=""{% url 'news:index' %}"" target="_blank">
				<div class="zaobao95 obese"><img src="{% static 'news/images/logo.jpg' %}" border="0" class="obese000 bottom">
                    </div>
				<div class="zaobao95 anorexic"><img src="{% static 'news/images/logo.jpg' %}" border="0" class="anorexic bottom">
                    </div>
				</a>
			</div>
      <div id="leaderboard"><div id="dfp-ad-lb1-wrapper" class="dfp-tag-wrapper">
<div id="dfp-ad-lb1" class="dfp-tag-wrapper" data-override="1">
    <script type="text/javascript">
            googletag.cmd.push(function() {
            googletag.display("dfp-ad-lb1");
        });
      </script>
</div>
</div></div>
    </div>

  </header>
</section>
<div id="victoria-secret" style=""><i class="fa fa-venus"></i></div>

  </div>
</div>
 <div class="container page-wrapper" id="CommonWealth">
 	<div id="NotCommon" class="row featured-top-wrapper">

 		<div class="row-eq-height">
 		 		</div>
 		<!-- ### Content Wrapper - START ### -->
 		<div class="row content-main-wrapper">


 			<div class="col-md-8 col-lg-8 boilerplate content-container" id="Milk">
 				 		      <section id="breadcrumbs">
					<a id="zb_breadcrumb_main" href="{% url 'news:index' %}" target="_blank">首页</a> <i class="fa fa-angle-right"></i> <a href="{% url 'news:index' %}" target="_blank">新闻</a> <i class="fa fa-angle-right"></i> <a href="{% url 'news:index' %}" target="_blank">{{news.category}}</a>
				</section>


        <!-- ### REGION: content_node - START ### -->
 				<div class="main-content">
         				        <div id="block-views-b121995c7bcfcd5cfd5fdf25a02d8c43" class="block block-views">
  <div class="content">
    <div class="view view-zb2016-node-content view-id-zb2016_node_content view-display-id-zb2016_node_content view-dom-id-fe1f460ed1128c4034cf4d359e7a1a39">

      <div class="view-content">
        <div class="views-row views-row-1 views-row-odd views-row-first views-row-last">
    <article id="MainCourse" class="cornwall" about="/znews/greater-china/story20181104-904581" typeof="sioc:Item foaf:Document">
  <div class="body-content">
    <h1>{{news.title}}</h1><aside class="trackme"><span class="datestamp date-published meta-date-published">发布<i>/</i>{{news.created_time}}</span><span class="contributor meta-byline">文<i>/</i><a href="#" target="_blank">李向民</a></span><span class="publication">来自<i>/</i><span class="lineage-item lineage-item-level-0"><a href="#" target="_blank">{{news.category}}</a></span><span class="lineage-item lineage-item-level-0">{{news.category}}</span><span class="hierarchical-select-item-separator">›</span><span class="lineage-item lineage-item-level-1"><a href="#" target="_blank">蜘蛛网</a></span></span></aside><div class="media-holder main"><!--0 video, 1 or multiple image -->
<div style="display:none;"></div>
<div class="loadme">
    <picture title="{{news.title}}">
        <img class="  lazyloaded" src="{{news.article_image}}" alt="" title="{{news.title}}">
    </picture>
    <figcaption>{{news.title}}</figcaption></div></div>
      <style>
.tooltipster-shadow {
	border-radius: 5px;
	background: #fff;
	box-shadow: 0px 0px 14px rgba(0,0,0,0.3);
	color: #2c2c2c;
}
.tooltipster-shadow .tooltipster-content {
	font-family: 'Arial', sans-serif;
	font-size: 14px;
	line-height: 16px;
	padding: 8px 10px;
}
.tooltipster-text-bold{
	font-size: 12px;
    font-weight: bold;
    text-align: left;
    line-height: 16px;
    height: 16px;
    position: relative;
    color: #000;
}
.tooltipster-text{
	font-size: 12px;
    text-align: left;
    line-height: 22px;
    color: #666;
}
</style>
      <div id="FineDining" class="article-content-container">
<p>{{news.article_content}}</p>


    <div id="dfp-ad-imu1-wrapper" class="dfp-tag-wrapper">
    <script type="text/javascript">
            googletag.cmd.push(function() {
            googletag.display("dfp-ad-imu1");
        });
      </script>
</div>

</div>
    </div></article>
        </div>
      </div>
    </div>
  </div>
                                </div>
                </div>
        <!-- ### REGION: content_node - END ### -->
<div id="ob_holder" style="display: none;"><script type="text/javascript" src="{% static news/js/widgetGlobalEvent" charset="UTF-8" async=""></script></div><div class="OUTBRAIN_AR_1" data-src="" data-widget-id="AR_1" data-ob-template="#" data-ob-mark="true" data-browser="chrome" data-os="win32" data-dynload="" data-idx="0" id="outbrain_widget_0"><div class="ob-widget ob-two-rows-strip-layout CR_1">
  </div></div>
  </div>
</div>
 				</div>
 				 			</div>
{% endif  %}

mysite/news/templates/news/index.html
{% load static %}
<html lang="en" >
<head>
<title>首页</title>
<link rel="stylesheet" type="text/css" href="{% static 'news/css/bootstrap.3.3.0.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'news/css/animate.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'news/css/owl.carousel.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'news/css/style-zbsg.css' %}">
<script src="{% static 'news/js/jquery-1.11.1.min.js' %}"></script>
<!--<script src="/sites/all/themes/zb2016/assets/js/jquery-1.10.2.min.js"></script>-->
<script src="{% static 'news/js/bootstrap.3.3.1.min.js' %}"></script>
<script src="{% static 'news/js/html5.js' %}"></script>
<script src="{% static 'news/js/jquery-checkator.js' %}"></script>
<script src="{% static 'news/js/rAF.js' %}"></script>
<script src="{% static 'news/js/app.lib.min.js' %}"></script>
<script src="{% static 'news/js/ads_checker.js' %}"></script>
<script src="{% static 'news/js/adblockDetector.js' %}"></script>
<!-- ### JS loaded check ### -->
<script src="{% static 'news/js/app_checker.js' %}"></script>
<!-- LOTAME LIBRARY -->
<script src="{% static 'news/js/Bootstrap.js' %}"></script>
</head>
<body class="html front not-logged-in no-sidebars page-node front home-global section-0-node" style="">
<style>
.zaobao95.obese{height:44px;}
.zaobao95.obese img{background:#fff;}
.zaobao95.anorexic img{background:#a50034;}
.zaobao95.anorexic{height:44px;}
.zaobao95{position:relative;margin:0 auto;clear:both;}
.zaobao95 img{position:absolute;left:0;}
.zaobao95 img.top{animation-name:fade;animation-timing-function:ease-in-out;animation-iteration-count:infinite;animation-duration:5s;animation-direction:alternate;}
@keyframes fade{
	0%{opacity:1;}
	25%{opacity:1;}
	75%{opacity:0;}
	100%{opacity:0;}
}

.spinner{height:34px;width:34px;margin:-4px 2px 0 0;position:relative;color:#fff;display:inline-block;}
.spinner:before{position:absolute;content:'';height:calc(100% + 1px);width:calc(100% + 1px);border:2px dotted #ffcc00;top:0;left:0;border-radius:inherit;animation:spin 10s linear infinite;}
.spinner,.spinner img{border-radius:50%;-moz-border-radius:50%;-khtml-border-radius:50%;-webkit-border-radius:50%;}
.spinner img{width:29px!important;margin:3px;}
img.spin{display:inline-block;width:30px!important;height:auto!important;margin:-2px 2px 0 0;animation:spin 4s linear infinite;}
@keyframes spin{
100%{transform: rotateZ(360deg);}
}
</style>
	  <!-- logo-->
<div id="zaobao-id" class="row">
      <div id="zaobao-brand">
				<a href="http://www.zaobao.com/" target="_blank">
				<div class="zaobao95 obese"><img src="{% static 'news/images/logo.jpg' %}" border="0" class="obese000 bottom"><img src="{% static 'news/images/logo.jpg' %}" border="0" class="obese000 top"></div>
				<div class="zaobao95 anorexic"><img src="{% static 'news/images/logo.jpg' %}" border="0" class="anorexic bottom"><img src="{% static 'news/images/logo.jpg' %}" border="0" class="anorexic top"></div>
				</a>
			</div>
</div>

     <!-- 新闻-->
<div class="container home-global page-top-wrapper page" id="CommonWealth">
	<div id="NotCommon" class="row featured-top-wrapper">
		<div id="QueenGiggles" class="row row-eq-height plate">
			<div class="col-xs-12 col-sm-12 col-md-4 col-lg-push-4 col-md-push-4 global-rotator" id="ChangingTheGuard">
					<!--图片新闻模块-->
   				<section class="col-xs-12 col-sm-12 col-md-12" id="billboard" style="clear:both;position:relative;">
<div class="owl-carousel owl-theme owl-loaded" data-region="homepageRotator">
	<div class="owl-stage-outer">
			<div class="owl-stage" style="transform: translate3d(-1424px, 0px, 0px); transition: all 0s ease 0s; width: 4272px;">
			<div class="owl-item cloned" style="width: 356px; margin-right: 0px;"></div>
			<div class="owl-item cloned" style="width: 356px; margin-right: 0px;"></div>
			<div class="owl-item" style="width: 356px; margin-right: 0px;"></div>
			<div class="owl-item" style="width: 356px; margin-right: 0px;"></div>
			<div class="owl-item active" style="width: 356px; margin-right: 0px;">
				<div class="views-row views-row-3 views-row-odd">
    <div  class="ds-1col node node-article view-mode-rotator  clearfix">
         
        {% for image_text in image_text %}
  <a href="{% url 'news:detail' image_text.id %}" data-path="node" data-nid="904589" target="_blank">
	  <img typeof="foaf:Image" src="{{image_text.article_image}}" width="800" height="500" alt="" title={{"news_list[image_text].title"}}>
	  <figcaption><b>{{image_text}}</b>
	  </figcaption>
		</a>
         {% endfor %}

				</div>

  </div></div>

		</div>
	</div>
</div>
	</section>

			</div>
				<script src="{% static 'news/js/home-rotator.js' %}"></script>
					<!--即时新闻-->
					<div class="col-xs-12 col-sm-6 col-md-4 col-lg-push-4 col-md-push-4 global-realtime" id="TheGuardsMarch">
      					<section class="row" id="MonkeysLearn">
                            <h2>即时新闻</h2>
                            <div role="tabpanels" id="ByWatchingMe">
	  <ul class="nav nav-tabs" role="tablist" id="RealTimeNav">
		<li role="presentation" class="col-md-4 col-sm-4 col-xs-4 active"><a href="#" aria-controls="RT-cn" role="tab" data-toggle="tab" data-title="中国" data-region="realtime_news_tab" class="analytics_onclick" target="_blank">中国</a></li>
		<li role="presentation" class="last col-md-4 col-sm-4 col-xs-4"><a href="#" aria-controls="RT-global" role="tab" data-toggle="tab" data-title="国际" data-region="realtime_news_tab" class="analytics_onclick" target="_blank">国际</a></li>
		<li role="presentation" class="col-md-4 col-sm-4 col-xs-4"><a href="#" aria-controls="RT-sg" role="tab" data-toggle="tab" data-title="科技" data-region="realtime_news_tab" class="analytics_onclick" target="_blank">科技</a></li>
	  </ul>

	  <div class="tab-content">
        <!--中国-->

        <div role="tabpanel" class="tab-pane active animated fadeIn" id="RT-cn"><ul class="bananas">
          
            {% for i in break_list2  %}
        <li class="" data-index="{{i}}">
          <div  class="ds-1col node node-article view-mode-realtime_listing  clearfix">
            <a href="{% url 'news:detail' i.id %}">
              <em>{{i.views}}</em><span>{{i}}</span>  </a>
          </div>
        </li>
          {% endfor %}


    </ul><a href="#" class="btn"><em>更多</em></a></div>
        <!--国际-->

		<div role="tabpanel" class="tab-pane animated fadeIn" id="RT-global"><ul class="bananas">
            
            {% for i in break_list1  %}
        <li class="" data-index="{{i}}">
          <div  class="ds-1col node node-article view-mode-realtime_listing  clearfix">
            <a href="{% url 'news:detail'  i.id %}">
              <em>{{i.views}}</em><span>{{i}}</span>  </a>
          </div>
        </li>
          {% endfor %}

    </ul><a href="#" class="btn"><em>更多</em></a></div>
        <!--科技-->
		<div role="tabpanel" class="tab-pane animated fadeIn" id="RT-sg"><ul class="bananas">
          
            {% for i in break_list3  %}
        <li class="" data-index="{{i}}">
          <div  class="ds-1col node node-article view-mode-realtime_listing  clearfix">
            <a href="{% url 'news:detail'  i.id %}">
              <em>{{i.views}}</em><span>{{i}}</span>  </a>
          </div>
        </li>
          {% endfor %}

    </ul><a href="#" class="btn"><em>更多</em></a></div>

	  </div>

	</div>
                        </section>
                    </div>
					<!--今日焦点-->
                    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-pull-8 col-md-pull-8" id="global-latest-focus">
                        <section id="piping-hot">
                            <h3>今日焦点</h3>
  	                        <div class="view view-zb2016-listing view-id-zb2016_listing view-display-id-zb2016_zbcom_prime_news view-dom-id-6c0bc42285f005129eb022ac3708dc88 jquery-once-1-processed">
	    	                  <div class="view-content">
	                              <ul class="post-list">

                                      
                                      {% for i in hot_list  %}
                                      <li class="post-item " data-index="{{i}}">
                                        <div class="ds-1col node node-article view-mode-title_only  clearfix">
                                          <a href="{% url 'news:detail' i.id %}" data-path="node" data-nid="904581" target="_blank">
                                            <div class="post-detail">
                                              <span class="post-title">{{i}}</span>
                                              <span class="datestamp hide-default">{{i.created_time}}</span>
                                            </div>
                                          </a>
                                        </div>
                                      </li>
                                      {% endfor %}

                                  </ul>
                              </div>
                            </div>
                        </section>
                    </div>
        </div>
    </div>
</div>
</body>
</html>